apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: generic-apps-onboarding
  namespace: argocd
spec:
  generators:
    # Cross-reference parsed directory names with explicitly labeled target clusters
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/vedantaggrawal/repo-app-gitops.git
              revision: HEAD
              directories:
                - path: 'apps/*/*'
          - clusters:
              selector:
                matchLabels:
                  environment: '{{path.basename}}'
  template:
    metadata:
      # Creates deterministic App names like 'dev-devops-test-webserver'
      name: '{{path.basename}}-{{path[1]}}'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/vedantaggrawal/repo-helm-chart.git
          path: .
          targetRevision: HEAD
          helm:
            valueFiles:
              - $values/{{path}}/values.yaml
        - repoURL: https://github.com/vedantaggrawal/repo-app-gitops.git
          targetRevision: HEAD
          ref: values
      destination:
        # Dynamically bound target cluster properties inherently preventing cross-env leakage
        server: '{{server}}'
        namespace: '{{path[1]}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
