replicaCount: 1

image:
  repository: ghcr.io/vedantaggrawal/repo-app-release
  tag: "v1.0.4"

imagePullSecrets:
  - name: ghcr-pull-secret

envVariables:
  ENV: "local"
  LOG_LEVEL: "debug"

ingress:
  enabled: true
  className: cilium
  hosts:
    - host: local.webserver.internal
      paths:
        - path: /
          pathType: Prefix
