replicaCount: 1

image:
  tag: "sha-2eda80b"

imagePullSecrets:
  - name: ghcr-pull-secret

envVariables:
  ENV: "development"
  LOG_LEVEL: "debug"

ingress:
  enabled: true
  hosts:
    - host: dev.webserver.internal
      paths:
        - path: /
          pathType: Prefix
