replicaCount: 1

image:
  repository: ghcr.io/vedantaggrawal/repo-app
  tag: "sha-d9b12d1"

imagePullSecrets:
  - name: ghcr-pull-secret

envVariables:
  ENV: "development"
  LOG_LEVEL: "debug"

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: dev.webserver.internal
      paths:
        - path: /
          pathType: Prefix
